---
title: "About the study"
---

## **Assessing the challenges to conducting suicide research faced by students and early career scientists**

**There is broad consensus that researchers seeking to describe, explain, predict, and prevent suicide face unique challenges**. Researchers consistently report a range of barriers to conducting research that are specific to questions related to suicide (for e.g., Home et al., 2017, Nugent et al., 2019, Berk et al., 2014, Jobes et al., 2009, Bailey et al., 2020, Lakeman & Fitzgerald, 2009; Oquendo & Porras-Segovia, 2020, Caves Sivaraman & Naumann, 2020, Andriessen et al., 2019, King & Kramer, 2008; Pearson et al., 2001; Prinstein, 2008; Zayas et al., 2008; Gibbons et al., 2010). **If established suicidologists are consistently challenged by these issues then it is probable that they pose significant challenges and barriers to the next generation of suicide researchers, who may not have the same level of support, knowledge of, or access to critical resources in mitigating these challenges.**

Although there is an emerging movement to provide mentorship and resources to early career researchers (ECRs) in suicidology (Han & Procter, 2020; Russell, 2018), *there are no published studies presenting data on the specific needs and challenges that ECRs face when conducting suicide research.* **The goal of the present study is to address this gap by evaluating the research-related needs and concerns of the next generation of suicide researchers**.

### Click here to learn more about how you can participate!

The study is being conducted by Abby Ridge-Anderson, Ph.D. (Principal Investigator), Rokas Perskaudas, Ph.D. (Co-Investigator) and David A. Jobes (Co-Investigator). This study has been approved by the Catholic University of America IRB (#23-0012-Ridge-Anderson, A.). Please contact Dr. Ridge-Anderson at [06anderson\@cua.edu](mailto:06anderson@cua.edu){.email} if you have questions about the study.
