---
title: " "
---

## <br>

# <b>Resources for suicide researchers<b>

## <br>

## <b>Networking<b>

|                                                                                                                 |                                                                                                                                                                                                                                                                          |     |                                                                                                                                                 |     |                                                           |
|-----------|-------------------|-----------|-----------|----|:---------:|
|                                                                                                                 | <font size="4">[**About**]{.underline}</font>                                                                                                                                                                                                                            |     | <font size="4">[**Notes**]{.underline}</font>                                                                                                   |     | <font size="4">[**Suicide-specific?**]{.underline}</font> |
| [netECR: International Network of Early Career Researchers in Suicide and Self-harm](https://netecr.org/)       | We are an independent, international network of Early Career Researchers (ECRs) working in suicide and self-harm -- netECR! Through netECR, we aim to facilitate collaborations, networking, and mutual support for ECRs in the field of suicide and self-harm research. |     |                                                                                                                                                 |     |                            ✔️                             |
| [Suicide Prevention Research Impact NeTwork (SPRINT)](https://www.hsrd.research.va.gov/centers/core/sprint/)    | One of SPRINT's main objectives is to build and sustain a collaborative network of VHA and non-VHA researchers and suicide prevention centers of excellence dedicated to conducting high-quality, high-priority, and high impact health services SP research.            |     | To connect with SPRINT & start receiving the monthly Newsletter, complete [this form](https://crisredcap.uams.edu/redcap/surveys/?s=MLWA77RAXT) |     |                            ✔️                             |
| SPRINT Early Career Investigator Quarterly Meetings                                                             |                                                                                                                                                                                                                                                                          |     | Join by emailing: [SuicidePreventionRes\@va.gov](mailto:SuicidePreventionRes@va.gov)                                                            |     |                            ✔️                             |
| [Suicide Prevention Research and Impact Network (SPRIN)](https://www.qub.ac.uk/sites/suicidepreventionnetwork/) | The Suicide Prevention Research and Impact Network (SPRIN) is a newly established network which aims to strengthen research-practice connections in the field of suicide prevention and improve the evidence-base.                                                       |     |                                                                                                                                                 |     |                            ✔️                             |

## <b>Suicide Organizations & Conferences<b>

|                                                                                                                                                 |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |     |                                               |     |                                                           |
|---------------|-------------------------|----|------------|---|:------------:|
|                                                                                                                                                 | <font size="4">[**About**]{.underline} </font>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |     | <font size="4">[**Notes**]{.underline}</font> |     | <font size="4">[**Suicide-specific?**]{.underline}</font> |
| [Suicide Research Symposium](https://www.suicideresearchsymposium.com/)                                                                         | The SRS was developed to disseminate suicide research, a much needed initiative for suicide prevention.                                                                                                                                                                                                                                                                                                                                                                                                                                             |     | Held in April, online                         |     |                            ✔️                             |
| [Suicide Cultures Conference](https://www.ed.ac.uk/suicide-cultures/suicide-cultures-events/conference2023)                                     | The conference will aim to provide a space where researchers from diverse disciplinary backgrounds can come together with policy-makers, practitioners and community-members to discuss, deliberate and reflect on the role of 'culture/s' in shaping suicide, suicide research, and suicide prevention.                                                                                                                                                                                                                                            |     | Held in June, Edinburgh, UK and online        |     |                            ✔️                             |
| [Suicide & Self-harm Early & Mid-Career Researchers' Forum (EMCRF)](https://suicideresearch.info/early-mid-career-researchers-emcr-forum-2023/) | The EMCR Forum will yield opportunities for investigators at an early stage of their career to receive the advice and guidance of more senior scientists in the field and create a supportive context for EMCRs to share their experiences and discuss the challenges faced in suicide and self-harm research, as well as fostering potential future research collaborations. The Forum also provides the opportunity to present your latest research and study projects in progress to colleagues, peers, health professionals, and policy makers. |     | Held in June, Glasgow, UK                     |     |                            ✔️                             |
| [International Association for Suicide Prevention (IASP)](https://www.iasp.info/goldcoast2021/)                                                 | The IASP World Congress is the primary global collaborative opportunity for expert thinking related to suicide and suicide prevention, bringing together academics, researchers, practitioners, those with lived experience, diverse backgrounds, and innovators associated with suicide prevention efforts or working within suicide prevention related topics.                                                                                                                                                                                    |     |                                               |     |                            ✔️                             |
| [International Academy of Suicide Research](https://suicide-research.org/)                                                                      | The International Academy for Suicide Research is an organization that promotes high standards of research and scholarship in the field of suicidal behaviour by fostering communication and co-operation among scholars engaged in such research.                                                                                                                                                                                                                                                                                                  |     |                                               |     |                            ✔️                             |
| [IASR/AFSP International Summit on Suicide Research](https://suicideresearchsummit.org/)                                                        | The Summit is sponsored by the International Academy of Suicide Research in partnership with the American Foundation for Suicide Prevention.                                                                                                                                                                                                                                                                                                                                                                                                        |     | Held in October, location varies              |     |                            ✔️                             |
| [American Association of Suicidology](https://suicidology.org/)                                                                                 | The membership of AAS includes mental health and public health professionals, researchers, suicide prevention and crisis intervention centers, school districts, crisis center volunteers, survivors of suicide loss, attempt survivors, and a variety of lay persons who have in interest in suicide prevention.                                                                                                                                                                                                                                   |     |                                               |     |                            ✔️                             |

## <b>Training<b>

|                                                                                                                                                                                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |     |                                                                                                                                                              |     |                                                           |
|---------------|--------------------------|----|-------------|----|:-----------:|
|                                                                                                                                                                                                    | <font size="4">[**About**]{.underline}</font>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |     | <font size="4">[**Notes**]{.underline}</font>                                                                                                                |     | <font size="4">[**Suicide-specific?**]{.underline}</font> |
| [AFSP Grants & Research Training Series](https://afsp.org/research-funding-opportunities-and-resources#powerpoint-presentations)                                                                   | Intended for young investigators, postdoctoral fellows, and investigators in suicide research, these presentations provide methodological considerations and grant application best practices for those who apply for and receive grants in suicide research from AFSP and the larger research community.                                                                                                                                                                                                                                                                                                                                                             |     | Topics: Establishing psychometrics; Power analysis; Research methods for suicide studies; Research plan development                                          |     |                            ✔️                             |
| [Suicide Prevention Research Methods for Early Career Researchers Training Series](https://suicide-research.org/suicide-prevention-research-methods-for-early-career-researchers-training-series/) | A series of virtual trainings that introduces some of the essential issues specific to suicide prevention research, for early-career researchers or those in the scientific community from other research disciplines. The series includes three 2.5-hour recordings of sessions that were conducted virtually via Zoom Webinar. They provide knowledge and tools for early career researchers who want to engage in high-level suicide research.                                                                                                                                                                                                                     |     |                                                                                                                                                              |     |                            ✔️                             |
| [Training in Comparative Effectiveness Research for Suicide Prevention](https://causalab.sph.harvard.edu/suicideprevention/)                                                                       | This interdisciplinary program is designed to train young investigators on modern causal inference methods for research on suicide prevention. The program trains both (i) researchers who have causal inference expertise, but not necessarily subject-matter expertise in suicide prevention, and (ii) researchers who have subject-matter expertise in suicide prevention, but not necessarily causal inference expertise. By bringing together investigators with interests ranging from predominantly methodological to predominantly substantive, the program facilitates cross-fertilization of ideas that will result in better tools for suicide prevention. |     | Both doctoral students (predoc trainees) and postdoctoral researchers (postdoc trainees) who are U.S. citizens or permanent residents are eligible to apply. |     |                            ✔️                             |

## <b>Templates & examples<b>

|                                                                                                                |                                                                                                                                                                                                                                                                                                                                                                                                        |     |                                                                                                                                                                             |     |                                                           |
|---------------|--------------------------|----|---------------|---|:---------:|
|                                                                                                                | <font size="4">[**About**]{.underline}</font>                                                                                                                                                                                                                                                                                                                                                          |     | <font size="4">[**Notes**]{.underline}</font>                                                                                                                               |     | <font size="4">[**Suicide-specific?**]{.underline}</font> |
| [Open Science in Suicide Research Database](https://osf.io/v6y3t/)                                             | This project contains the supplementary materials for Kirtley, O. J., Janssens, J. J., & Kaurin, A. (2022). Open Science in Suicide Research Is Open for Business. Crisis, 10.1027/0227-5910/a000859.                                                                                                                                                                                                  |     | As part of our editorial, we have created a living list of examples of studies on suicide or self-injury that use open science practices.                                   |     |                            ✔️                             |
| [Risk Management Resources from SPRINT](https://www.hsrd.research.va.gov/centers/core/sprint/risk_management/) | Provides: (a) resource guides and (b) templates for managing suicide risk in research participants. The resources included aim to address various research study types (e.g., surveys, qualitative methods, interventions, etc.), and to address safety in various stages of the research process (e.g., participant risk assessment, participant correspondence, tracking, language for IRB and DSMP) |     | Includes: Risk Management Protocols and Flow charts; Risk Documentation; Risk Management Training; Participant Resources; Data Safety Monitoring/Regulatory sample language |     |                            ✔️                             |

## <b>Measures<b>

|                                                                                                                                         |                                                                                                                                                                                                                                                                                                                                                  |     |                                               |     |                                                           |
|---------------|--------------------------|----|---------------|----|:---------:|
|                                                                                                                                         | <font size="4">[**About**]{.underline}</font>                                                                                                                                                                                                                                                                                                    |     | <font size="4">[**Notes**]{.underline}</font> |     | <font size="4">[**Suicide-specific?**]{.underline}</font> |
| [Measurement Resources for Suicide Prevention Research](https://www.hsrd.research.va.gov/centers/core/sprint/measurement_resources.cfm) | The SPRINT-Assistance in Selecting Suicide Indices Specialty Tool (S-ASSIST) is a summary table outlining the broad facets of suicidal thoughts and behaviors (i.e., not risk factors) that are captured within and across measures recommended by the working group of the PhenX Suicide Specialty Collection (with the addition of the PHQ-9). |     |                                               |     |                            ✔️                             |

## <b>Datasets<b>

|                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |     |                                                                                                  |     |                                                           |
|---------------|--------------------------|---|---------------|----|:---------:|
|                                                                                                                                                                                                  | <font size="4">[**About**]{.underline}</font>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |     | <font size="4">[**Notes**]{.underline}</font>                                                    |     | <font size="4">[**Suicide-specific?**]{.underline}</font> |
| [Inter-university Consortium for Political and Social Research (ICPSR)'s Research Data Ecosystem](https://www.icpsr.umich.edu/web/pages/ICPSR/index.html)                                        | ICPSR stores, curates, and provides access to scientific data so others can reuse the data and validate research findings.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |     | Includes 104 publicly available datasets with the subject term "suicide" or "suicide prevention" |     |                                                           |
| [An Introduction to the Army STARRS Survey Data Available through ICPSR](https://www.hsrd.research.va.gov/for_researchers/cyber_seminars/archives/video_archive.cfm?SessionID=5198&Seriesid=106) | This webinar introduces the data available from the Army STARRS suite of surveys that are available through ICPSR. Army STARRS and STARRS-LS were designed to comprehensively investigate risk factors and protective factors for suicide, suicide-related behavior, and other mental/behavioral health issues in Army Soldiers. Participants have now been interviewed multiple times. The webinar will describe how to access the data via ICPSR, give an overview of the questionnaires, and provide a brief review of some results already obtained from these data. Intended Audience: Researchers interested in mental health issues in Army Soldiers. |     |                                                                                                  |     |                            ✔️                             |
| [SPTD: Suicide Prevention Trials Database](https://www.hsrd.research.va.gov/centers/core/sprint/sptd.cfm)                                                                                        | The mission of the SPTD is to establish a publicly available and up-to-date database of study-level data from published trials of suicide prevention approaches. The database may be used for future systematic reviews or clinical practice guidelines, for identifying research gaps, and as an information resource for clinicians, patients, policymakers, and family members.                                                                                                                                                                                                                                                                           |     |                                                                                                  |     |                            ✔️                             |
| [Directory of free, open psychological datasets](https://osf.io/th8ew/)                                                                                                                          | Psychologists are not using large, existing, free data to its potential. We don't know what exists, what it contains, or how to use it without a huge investment. After our #SIPS2019 hackathon, we now have a list of 80 free, large datasets.                                                                                                                                                                                                                                                                                                                                                                                                              |     | Last updated 2019                                                                                |     |                                                           |

## <b>Resources for participants<b>

|                                                           |                                                                                                                                                                                                          |     |                                               |     |                                                           |
|---------------|--------------------------|----|---------------|----|:---------:|
|                                                           | <font size="4">[**About**]{.underline}</font>                                                                                                                                                            |     | <font size="4">[**Notes**]{.underline}</font> |     | <font size="4">[**Suicide-specific?**]{.underline}</font> |
| [988 Suicide & Crisis Lifeline](https://988lifeline.org/) | The Lifeline provides 24/7, free and confidential support for people in distress, prevention and crisis resources for you or your loved ones, and best practices for professionals in the United States. |     |                                               |     |                            ✔️                             |
| More to come!                                             |                                                                                                                                                                                                          |     |                                               |     |                                                           |

## <b>Research funding<b>

|              |     |     |     |
|--------------|-----|-----|-----|
| Coming soon! |     |     |     |
